name: Publish

on:
  release:
    types:
      - released

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.7]
        poetry-version: [1.2.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        env:
          POETRY_VERSION: ${{ matrix.poetry-version }}
        run: pip install poetry==$POETRY_VERSION
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build -n
